Repository naxuroqa/Venom, pull requests merged in 2018-12, with the labels that each got.

#459 Spelling: nospam → NoSpam
  src/ui/user_info_widget.ui
Labels: Priority: Low, Type: Bug

#460 VENOM-460: Convert banner text to objects
  .github/banner/venom.svg
Labels: Priority: Low, Type: Maintenance

#463 VENOM-184: Add support for voice and video calls
  README.md
  meson.build
  src/Main.vala
  src/av/AudioInPipeline.vala
  src/av/AudioOutPipeline.vala
  src/av/Photobooth.vala
  src/av/Pipeline.vala
  src/av/VideoInPipeline.vala
  src/av/VideoOutPipeline.vala
  src/core/Application.vala
  src/core/CallState.vala
  src/core/Logger.vala
  src/core/NotificationListener.vala
  src/core/Profile.vala
  src/meson.build
  src/testing/SettingsTest.vala
  src/testing/VideoSendBot.vala
  src/testing/meson.build
  src/testing/mocks/MockDhtNodeRepository.vala
  src/testing/mocks/MockNotificationListener.vala
  src/testing/mocks/MockSettingsDatabase.vala
  src/testing/mocks/MockToxSession.vala
  src/tox/SqliteMessageRepository.vala
  src/tox/ToxAVThread.vala
  src/tox/ToxCallAdapter.vala
  src/tox/ToxConferenceAdapter.vala
  src/tox/ToxFiletransferAdapter.vala
  src/tox/ToxFriendAdapter.vala
  src/tox/ToxSelfAdapter.vala
  src/tox/ToxSession.vala
  src/tox/ToxSessionThread.vala
  src/ui/add_contact_widget.ui
  src/ui/call_widget.ui
  src/ui/conference_window.ui
  src/ui/contact_list_widget.ui
  src/ui/conversation_window.ui
  src/ui/settings_widget.ui
  src/ui/venom.gresource.xml
  src/vapi/toxav.deps
  src/vapi/toxav.vapi
  src/vapi/toxcore.deps
  src/vapi/toxcore.vapi
  src/vapi/toxencryptsave.deps
  src/vapi/toxencryptsave.vapi
  src/view/AboutDialog.vala
  src/view/ApplicationWindow.vala
  src/view/CallWidget.vala
  src/view/ContactListEntry.vala
  src/view/ContactListEntryCompact.vala
  src/view/ContactListWidget.vala
  src/view/ConversationWindow.vala
  src/view/SettingsWidget.vala
  src/view/UserInfoWidget.vala
  src/viewmodel/ContactListEntryViewModel.vala
  src/viewmodel/ContactListViewModel.vala
Labels: Priority: Medium, Type: Enhancement

#469 VENOM-466: Fix crash when right clicking empty contact list
  src/view/ContactListWidget.vala
Labels: Priority: High, Type: Bug

#467 VENOM-467: Fix file send avatar not sending hash
  src/core/Profile.vala
  src/testing/mocks/MockToxSession.vala
  src/tox/ToxFriendAdapter.vala
  src/tox/ToxSession.vala
Labels: Priority: High, Type: Bug

#465 VENOM-465: Hide call buttons when remote is offline
  src/ui/conference_window.ui
  src/ui/contact_list_widget.ui
  src/ui/conversation_window.ui
  src/ui/message_widget.ui
  src/view/ConversationWindow.vala
Labels: Priority: Medium, Type: Bug

#472 VENOM-472: Remove unused code
  src/av/AVManager.vala
Labels: Priority: Low, Type: Maintenance
