Repository naxuroqa/Venom, pull requests merged in 2018-06, with the labels that each got.

#395 VENOM-395: Ignore testing folder from codecov
  codecov.yml
Labels: Priority: Low, Type: Mantainance

#396 VENOM-396: Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Priority: Low, Type: Enhancement

#394 VENOM-394: Catch toxcore startup errors
  src/core/Application.vala
  src/core/Interfaces.vala
  src/core/Logger.vala
  src/core/WidgetFactory.vala
  src/meson.build
  src/testing/mocks/MockLogger.vala
  src/ui/error_widget.ui
  src/ui/venom.gresource.xml
  src/view/ApplicationWindow.vala
  src/view/ErrorWidget.vala
Labels: Priority: Medium, Type: Enhancement

#397 VENOM-397: Update potfiles to include errordialog and widget
  po/POTFILES
  src/ui/friend_request_widget.ui
  src/ui/settings_widget.ui
Labels: Priority: Low, Type: Maintenance

#398 Fix a typo in readme
  README.md
Labels: Priority: Low, Type: Maintenance
